# ${DATA_PATH}: path/to/local/project/catalog
# stored in path/to/project/config/.env

# ----------------------------
# DATA CATALOG
# ----------------------------

project_data:
    type: folder
    filepath: ${DATA_PATH}

infra_25m:
    type: geotiff
    filepath: "${NINA_P}/154004_omfang_vern_og_bevaring/GIS-data_bevaring/infrastrukturindeksen_25x25m/Infra25m_25833.tif"

bioclimatic_zones:
    type: filegdb
    filepath: "${NINA_R}/GeoSpatialData/BiogeographicalRegions/Norway_PCA_klima/Original/20170614_Bioklima/20170614_Bioklima.gdb"
    layer: Soner2017
    year: 2017

ar50:
    type: filegdb
    filepath: "${NINA_R}/GeoSpatialData/LandCover/Norway_LandResource_AR50/Original/versjon20221321/Arealressurskart - AR50/0000_25833_ar50_gdb.gdb"
    layer: ar50_flate
    year: 2022

n50:
    type: filegdb
    filepath: "${NINA_R}/GeoSpatialData/Topography/Norway_N50/Original/N50 Kartdata FGDB-format/Basisdata_0000_Norge_25833_N50Kartdata_FGDB.gdb"
    layer: N50_Arealdekke_omrade
    year: 2021

fylke:
    type: filegdb
    filepath: "${NINA_R}/GeoSpatialData/AdministrativeUnits/Norway_AdministrativeUnits/Original/Norway_County/Administrative_enheter_fylker_2024_FGDB-format/Basisdata_0000_Norge_25833_Fylker2024_FGDB.gdb"
    layer: fylke
    year: 2024

fkb_vann:
    type: filegdb
    filepath: "/home/NINA.NO/willeke.acampo/Mounts/R/GeoSpatialData/Topography/Norway_FKB/Original/FKB-Vann FGDB-format/Basisdata_0000_Norge_5973_FKB-Vann_FGDB.gdb"
    layer: fkb_vann_omrade

# ----------------------------
# METADATA
# ----------------------------

metadata:
    identification:
        title:
            en: english title
            no: norwegian title (bokmål)
        description:
            en: english title
            no: norwegian title (bokmål)
        keywords:
            en:
                - spatial data
            no:
                - romlige data
        keywords_type: theme
        terms_of_service: https://opensource.org/license/mit/
        url: http://example.org
    license:
        name: The MIT License (MIT)
        url: https://opensource.org/license/mit/
    provider:
        name: Organization Name
        url: http://example.org
    contact:
        name: Lastname, Firstname
        position: Position Title
        address: Mailing Address
        city: City
        stateorprovince: Administrative Area
        postalcode: Zip or Postal Code
        country: Country
        phone: +xx-xxx-xxx-xxxx
        email: you@example.org
        url: Contact URL
        hours: Hours of Service
        instructions: During hours of service.  Off on weekends.
        role: pointOfContact
